name: Integration Test

on:
  push:
    branches:
      - 'master'


jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble debug app
        run: ./gradlew assembleDebug

      - name: Export Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble app instrumentation tests
        run: ./gradlew assembleDebugAndroidTest

      - name: Export App Test APK
        uses: actions/upload-artifact@v2
        with:
          name: app_androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  firebase:
    name: Execute Test Lab
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Download debug APK
        uses: actions/download-artifact@v2
        with:
          name: apk

      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 270.0.0
          service_account_key: ${{ secrets.GCLOUD_AUTH_DEVICE_LAB }}

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID_DEVICE_LAB }}

      - name: Download App test APK
        uses: actions/download-artifact@v2
        with:
          name: app_androidTest

      - name: Run App Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app-debug.apk --test app-debug-androidTest.apk --use-orchestrator --device model=Pixel2,version=28,locale=en,orientation=portrait
